# Generated by Django 5.2.6 on 2025-12-26 07:35

import uuid
from django.db import migrations, models


def drop_products_table(apps, schema_editor):
    table_sql = 'DROP TABLE IF EXISTS "products_product"'
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"{table_sql} CASCADE;")
    else:
        schema_editor.execute(f"{table_sql};")


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(drop_products_table, migrations.RunPython.noop)],
            state_operations=[migrations.DeleteModel(name="Product")],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
